spring:
  profiles:
    active:
    - dev
---
server:
  port: 3001

spring:
  profiles: dev #测试环境
  application:
    name: config-client
  cloud:
    ##Config客户配置
    config:
      label: master #分支名称
      name: config #配置文件名称(模块应用）
      profile: dev #读取后缀名称 上述3个综合:master分支上config-dev.yml的配置文件被读取
      uri: http://localhost:2030 #配置中心地址

    ##consul
    consul:
      host: 192.168.174.129 #consul服务器的主机地址
      port: 8500 #consul服务器的ip地址
      discovery:
        #是否需要注册
        register: true
        #注册的实例ID (唯一标志)
        instance-id: ${spring.application.name}-${server.port}
        service-name: ${spring.application.name}
        #服务的请求端口
        port: ${server.port}
        #指定开启ip地址注册
        prefer-ip-address: true
        #当前服务的请求ip
        ip-address: ${spring.cloud.client.ip-address}
  #        heartbeat:
  #          enabled: true


  ##rabbitmq相关配置
  rabbitmq:
    host: 192.168.174.129
    #这个端口号与RabitMQ管理界面所使用访问的端口号不同15672
    port: 5672
    username: guest
    password: guest

##暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*" #refresh
---
server:
  port: 3002

spring:
  profiles: test #测试环境
  application:
    name: config-client
  cloud:
    ##Config客户配置
    config:
      label: master #分支名称
      name: config #配置文件名称(模块应用）
      profile: dev #读取后缀名称 上述3个综合:master分支上config-dev.yml的配置文件被读取
      uri: http://localhost:2030 #配置中心地址

    ##consul
    consul:
      host: 192.168.174.129 #consul服务器的主机地址
      port: 8500 #consul服务器的ip地址
      discovery:
        #是否需要注册
        register: true
        #注册的实例ID (唯一标志)
        instance-id: ${spring.application.name}-${server.port}
        service-name: ${spring.application.name}
        #服务的请求端口
        port: ${server.port}
        #指定开启ip地址注册
        prefer-ip-address: true
        #当前服务的请求ip
        ip-address: ${spring.cloud.client.ip-address}
  #        heartbeat:
  #          enabled: true


  ##rabbitmq相关配置
  rabbitmq:
    host: 192.168.174.129
    #这个端口号与RabitMQ管理界面所使用访问的端口号不同15672
    port: 5672
    username: guest
    password: guest

##暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*" #refresh